// estyped generates type-safe Go field definitions from Elasticsearch index mappings.
//
// Given an Elasticsearch mapping JSON file, it produces a Go source file containing
// typed [estype.Field] definitions for every field found in the mapping.
// This is similar to how sqlc generates Go code from SQL schemas — typos in field
// names become compile errors instead of silent runtime bugs.
//
// There are two output modes:
//
// Constant mode (default): generates individual constants.
//
//	estyped -mapping mapping.json -out model.go -package model
//
// Struct mode: generates a struct variable so fields are accessed as model.Sample.FieldName.
//
//	estyped -mapping mapping.json -out model.go -package model -name Sample
//
// The mapping JSON can be in either the full Get Mapping API format:
//
//	{"mappings": {"properties": { ... }}}
//
// or the abbreviated properties-only format:
//
//	{"properties": { ... }}
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
	"text/template"

	"github.com/tomtwinkle/es-typed-go/estype"
)

type fieldEntry struct {
	ConstName string
	FieldName string
	Path      string
	Type      string
}

type templateData struct {
	Package string
	Name    string
	Fields  []fieldEntry
}

// constTemplate generates individual constants (default mode).
var constTemplate = template.Must(template.New("const").Parse(`// Code generated by estyped; DO NOT EDIT.

package {{ .Package }}

import "github.com/tomtwinkle/es-typed-go/estype"

{{ range .Fields -}}
// Field{{ .ConstName }} is the "{{ .Path }}" field (type: {{ .Type }}).
const Field{{ .ConstName }} estype.Field = "{{ .Path }}"
{{ end -}}
`))

// structTemplate generates a struct variable for grouped field access (struct mode).
var structTemplate = template.Must(template.New("struct").Parse(`// Code generated by estyped; DO NOT EDIT.

package {{ .Package }}

import "github.com/tomtwinkle/es-typed-go/estype"

// {{ .Name }} provides typed field names for the Elasticsearch index mapping.
var {{ .Name }} = struct {
{{- range .Fields }}
	{{ .FieldName }} estype.Field
{{- end }}
}{
{{- range .Fields }}
	{{ .FieldName }}: "{{ .Path }}",
{{- end }}
}
`))

func main() {
	mappingPath := flag.String("mapping", "", "path to Elasticsearch mapping JSON file (required)")
	outPath := flag.String("out", "", "output Go file path (required)")
	pkgName := flag.String("package", "", "Go package name for the generated file (required)")
	structName := flag.String("name", "", "struct variable name for grouped field access (optional; omit for constant mode)")
	flag.Parse()

	if *mappingPath == "" || *outPath == "" || *pkgName == "" {
		flag.Usage()
		os.Exit(1)
	}

	data, err := os.ReadFile(*mappingPath)
	if err != nil {
		log.Fatalf("failed to read mapping file %s: %v", *mappingPath, err)
	}

	mapping, err := estype.ParseMapping(data)
	if err != nil {
		log.Fatalf("failed to parse mapping: %v", err)
	}

	entries := make([]fieldEntry, 0, len(mapping.Fields))
	for _, f := range mapping.Fields {
		entries = append(entries, fieldEntry{
			ConstName: toPascalCase(f.Path),
			FieldName: toStructFieldName(f.Path),
			Path:      f.Path,
			Type:      fieldType(f.Type),
		})
	}

	var buf bytes.Buffer
	td := templateData{
		Package: *pkgName,
		Name:    *structName,
		Fields:  entries,
	}

	if *structName != "" {
		if err := structTemplate.Execute(&buf, td); err != nil {
			log.Fatalf("template execution failed: %v", err)
		}
	} else {
		if err := constTemplate.Execute(&buf, td); err != nil {
			log.Fatalf("template execution failed: %v", err)
		}
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("go/format failed: %v\n\nGenerated source:\n%s", err, buf.String())
	}

	if err := os.WriteFile(*outPath, formatted, 0o644); err != nil {
		log.Fatalf("failed to write %s: %v", *outPath, err)
	}

	fmt.Printf("wrote %s (%d fields)\n", *outPath, len(entries))
}

// toPascalCase converts a dot-separated ES field path to PascalCase.
// Used for constant names where all segments are concatenated.
// Examples:
//
//	"status"        → "Status"
//	"items.color"   → "ItemsColor"
//	"title.keyword" → "TitleKeyword"
func toPascalCase(path string) string {
	parts := strings.Split(path, ".")
	var result []string
	for _, part := range parts {
		subParts := strings.Split(part, "_")
		for _, sp := range subParts {
			if sp == "" {
				continue
			}
			result = append(result, strings.ToUpper(sp[:1])+sp[1:])
		}
	}
	return strings.Join(result, "")
}

// toStructFieldName converts a dot-separated ES field path to a struct field name.
// Each path segment is PascalCased and segments are joined with "_" to preserve
// the nesting structure.
// Examples:
//
//	"status"        → "Status"
//	"items.color"   → "Items_Color"
//	"field_name"    → "FieldName"
func toStructFieldName(path string) string {
	parts := strings.Split(path, ".")
	var result []string
	for _, part := range parts {
		subParts := strings.Split(part, "_")
		var segment []string
		for _, sp := range subParts {
			if sp == "" {
				continue
			}
			segment = append(segment, strings.ToUpper(sp[:1])+sp[1:])
		}
		result = append(result, strings.Join(segment, ""))
	}
	return strings.Join(result, "_")
}

// fieldType returns the type string for display, defaulting to "object" when empty.
func fieldType(t string) string {
	if t == "" {
		return "object"
	}
	return t
}
