// estyped generates type-safe Go field definitions from Elasticsearch index mappings.
//
// Given an Elasticsearch mapping JSON file, it produces a Go source file containing
// typed [estype.Field] definitions for every field found in the mapping.
// This is similar to how sqlc generates Go code from SQL schemas — typos in field
// names become compile errors instead of silent runtime bugs.
//
// There are two input modes:
//
// Mapping mode (default): reads an Elasticsearch mapping JSON file.
//
//	estyped -mapping mapping.json -out model.go -package model
//
// Struct mode: reads JSON struct tags from a Go type definition.
//
//	estyped -struct Product -out model.go
//
// In struct mode the tool parses all .go files in the current directory (or the
// directory of -file), finds the named type, and recursively extracts field paths
// from json struct tags.  This is the recommended usage with go:generate:
//
//	//go:generate go tool estyped -struct Product -out product_fields.go
//
// When the struct (or a pointer to it) implements [estype.MappingProvider] by
// defining a Mapping() method, the generator reads the returned [estype.Mapping]
// to determine the Elasticsearch type of each field.  The method body must contain
// a single return statement with a composite literal; more complex expressions are
// silently ignored and the field type falls back to "unknown".
//
// The Property field of each [estype.MappingField] entry accepts a typed
// property value from a constructor call such as [estype.NewTextProperty] or
// [estype.NewKeywordProperty], or [estype.FieldType] for a plain type name:
//
//	func (Product) Mapping() estype.Mapping {
//	   return estype.Mapping{
//
//	      Fields: []estype.MappingField{
//	          {Path: "status", Property: estype.NewKeywordProperty()},
//	          {Path: "title",  Property: estype.NewTextProperty()},
//	          {Path: "title.my_ngram", Property: estype.NewTextProperty()}, // Users can explicitly define sub-fields
//	          {Path: "price",  Property: estype.FieldType("integer")},
//	       },
//	    }
//	 }
//
// There are two output modes:
//
// Constant mode (default): generates individual constants.
//
//	estyped -mapping mapping.json -out model.go -package model
//
// Grouped mode: generates a struct variable so fields are accessed as model.Sample.FieldName.
//
//	estyped -mapping mapping.json -out model.go -package model -group Sample
//
// The mapping JSON can be in either the full Get Mapping API format:
//
//	{"mappings": {"properties": { ... }}}
//
// or the abbreviated properties-only format:
//
//	{"properties": { ... }}
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"text/template"

	"github.com/tomtwinkle/es-typed-go/estype"
	"golang.org/x/tools/go/packages"
)

type fieldEntry struct {
	ConstName string
	FieldName string
	Path      string
	Type      string
}

type templateData struct {
	Package string
	Name    string
	Fields  []fieldEntry
}

// modelTemplateData holds the data for the model output format, which nests fields
// inside a Fields sub-struct and optionally includes Alias and Index fields.
type modelTemplateData struct {
	Package  string
	Name     string
	Fields   []fieldEntry
	Alias    string
	Index    string
	HasAlias bool
	HasIndex bool
}

// constTemplate generates individual constants (default mode).
var constTemplate = template.Must(template.New("const").Parse(`// Code generated by estyped; DO NOT EDIT.

package {{ .Package }}

import "github.com/tomtwinkle/es-typed-go/estype"

{{ range .Fields -}}
// Field{{ .ConstName }} is the "{{ .Path }}" field (type: {{ .Type }}).
const Field{{ .ConstName }} estype.Field = "{{ .Path }}"
{{ end -}}
`))

// structTemplate generates a struct variable for grouped field access (struct mode).
var structTemplate = template.Must(template.New("struct").Parse(`// Code generated by estyped; DO NOT EDIT.

package {{ .Package }}

import "github.com/tomtwinkle/es-typed-go/estype"

// {{ .Name }} provides typed field names for the Elasticsearch index mapping.
var {{ .Name }} = struct {
{{- range .Fields }}
    {{ .FieldName }} estype.Field
{{- end }}
}{
{{- range .Fields }}
    {{ .FieldName }}: "{{ .Path }}",
{{- end }}
}
`))

// modelTemplate generates a unified model accessor with nested Fields, Alias, and Index.
// Used when -group is specified together with -struct and the source type implements
// estype.AliasProvider and/or estype.IndexProvider.
var modelTemplate = template.Must(template.New("model").Parse(`// Code generated by estyped; DO NOT EDIT.

package {{ .Package }}

import "github.com/tomtwinkle/es-typed-go/estype"

// {{ .Name }} is the unified model accessor for the Elasticsearch index.
// Access typed field names via {{ .Name }}.Fields, the canonical alias via
// {{ .Name }}.Alias, and the canonical index name via {{ .Name }}.Index.
var {{ .Name }} = struct {
    Fields struct {
{{- range .Fields }}
       {{ .FieldName }} estype.Field
{{- end }}
    }
{{- if .HasAlias }}
    Alias estype.Alias
{{- end }}
{{- if .HasIndex }}
    Index estype.Index
{{- end }}
}{
    Fields: struct {
{{- range .Fields }}
       {{ .FieldName }} estype.Field
{{- end }}
    }{
{{- range .Fields }}
       {{ .FieldName }}: "{{ .Path }}",
{{- end }}
    },
{{- if .HasAlias }}
    Alias: "{{ .Alias }}",
{{- end }}
{{- if .HasIndex }}
    Index: "{{ .Index }}",
{{- end }}
}
`))

func main() {
	mappingPath := flag.String("mapping", "", "path to Elasticsearch mapping JSON file")
	structType := flag.String("struct", "", "Go type name to read JSON struct tags from (alternative to -mapping)")
	filePath := flag.String("file", "",
		"Go source file for struct lookup (used with -struct; defaults to current directory)")
	outPath := flag.String("out", "", "output Go file path (required)")
	pkgName := flag.String("package", "", "Go package name for the generated file (defaults to $GOPACKAGE)")
	structName := flag.String("group", "",
		"group variable name for grouped field access (optional; omit for constant mode)")
	flag.Parse()

	// When invoked via go:generate, $GOPACKAGE is set automatically.
	if *pkgName == "" {
		*pkgName = os.Getenv("GOPACKAGE")
	}

	if *outPath == "" || *pkgName == "" {
		flag.Usage()
		os.Exit(1)
	}
	if *mappingPath == "" && *structType == "" {
		fmt.Fprintln(os.Stderr, "error: either -mapping or -struct is required")
		flag.Usage()
		os.Exit(1)
	}
	if *mappingPath != "" && *structType != "" {
		fmt.Fprintln(os.Stderr, "error: -mapping and -struct are mutually exclusive")
		flag.Usage()
		os.Exit(1)
	}

	var entries []fieldEntry

	if *structType != "" {
		// Struct-based parsing: extract field paths from JSON struct tags.
		srcDir := "."
		if *filePath != "" {
			srcDir = filepath.Dir(*filePath)
		}
		var (
			files []*ast.File
			err   error
		)
		entries, files, err = parseGoStruct(srcDir, *structType)
		if err != nil {
			log.Fatalf("failed to parse struct %s: %v", *structType, err)
		}

		// When -group is set in struct mode, generate the unified model format
		// (Fields sub-struct + optional Alias and Index fields) if the source
		// type implements AliasProvider or IndexProvider.
		if *structName != "" {
			alias, hasAlias := extractStringReturnMethod(files, *structType, "Alias")
			index, hasIndex := extractStringReturnMethod(files, *structType, "Index")

			if hasAlias || hasIndex {
				var buf bytes.Buffer
				mdata := modelTemplateData{
					Package:  *pkgName,
					Name:     *structName,
					Fields:   entries,
					Alias:    alias,
					Index:    index,
					HasAlias: hasAlias,
					HasIndex: hasIndex,
				}
				if err := modelTemplate.Execute(&buf, mdata); err != nil {
					log.Fatalf("template execution failed: %v", err)
				}
				formatted, err := format.Source(buf.Bytes())
				if err != nil {
					log.Fatalf("go/format failed: %v\n\nGenerated source:\n%s", err, buf.String())
				}
				if err := os.WriteFile(*outPath, formatted, 0o644); err != nil {
					log.Fatalf("failed to write %s: %v", *outPath, err)
				}
				fmt.Printf("wrote %s (%d fields, alias=%v, index=%v)\n", *outPath, len(entries), hasAlias, hasIndex)
				return
			}
		}
	} else {
		// Mapping-based parsing: existing behaviour.
		data, err := os.ReadFile(*mappingPath)
		if err != nil {
			log.Fatalf("failed to read mapping file %s: %v", *mappingPath, err)
		}

		mapping, err := estype.ParseMapping(data)
		if err != nil {
			log.Fatalf("failed to parse mapping: %v", err)
		}

		entries = make([]fieldEntry, 0, len(mapping.Fields))
		for _, f := range mapping.Fields {
			entries = append(entries, fieldEntry{
				ConstName: toPascalCase(f.Path),
				FieldName: toStructFieldName(f.Path),
				Path:      f.Path,
				Type:      fieldType(f.TypeName()),
			})
		}
	}

	var buf bytes.Buffer
	td := templateData{
		Package: *pkgName,
		Name:    *structName,
		Fields:  entries,
	}

	if *structName != "" {
		if err := structTemplate.Execute(&buf, td); err != nil {
			log.Fatalf("template execution failed: %v", err)
		}
	} else {
		if err := constTemplate.Execute(&buf, td); err != nil {
			log.Fatalf("template execution failed: %v", err)
		}
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("go/format failed: %v\n\nGenerated source:\n%s", err, buf.String())
	}

	if err := os.WriteFile(*outPath, formatted, 0o644); err != nil {
		log.Fatalf("failed to write %s: %v", *outPath, err)
	}

	fmt.Printf("wrote %s (%d fields)\n", *outPath, len(entries))
}

// toPascalCase converts a dot-separated ES field path to PascalCase.
// Used for constant names where all segments are concatenated.
// Examples:
//
//	"status"        → "Status"
//	"items.color"   → "ItemsColor"
//	"title.keyword" → "TitleKeyword"
func toPascalCase(path string) string {
	var b strings.Builder
	for part := range strings.SplitSeq(path, ".") {
		for sp := range strings.SplitSeq(part, "_") {
			if sp == "" {
				continue
			}
			b.WriteString(strings.ToUpper(sp[:1]))
			b.WriteString(sp[1:])
		}
	}
	return b.String()
}

// toStructFieldName converts a dot-separated ES field path to a struct field name.
// Each path segment is PascalCased and segments are joined with "_" to preserve
// the nesting structure.
// Examples:
//
//	"status"        → "Status"
//	"items.color"   → "Items_Color"
//	"field_name"    → "FieldName"
func toStructFieldName(path string) string {
	var b strings.Builder
	firstPart := true
	for part := range strings.SplitSeq(path, ".") {
		if !firstPart {
			b.WriteByte('_')
		}
		firstPart = false

		for sp := range strings.SplitSeq(part, "_") {
			if sp == "" {
				continue
			}
			b.WriteString(strings.ToUpper(sp[:1]))
			b.WriteString(sp[1:])
		}
	}
	return b.String()
}

// fieldType returns the type string for display, defaulting to "object" when empty.
func fieldType(t string) string {
	if t == "" {
		return "object"
	}
	return t
}

// parseGoStruct extracts fieldEntry values from a named Go struct type.
// It uses golang.org/x/tools/go/packages to perfectly resolve Types, ensuring
// future compatibility with Go language changes like type aliases and generics.
func parseGoStruct(srcDir, typeName string) ([]fieldEntry, []*ast.File, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedImports,
		Dir:  srcDir,
	}

	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		return nil, nil, fmt.Errorf("failed to load package in %s: %w", srcDir, err)
	}
	if len(pkgs) == 0 {
		return nil, nil, fmt.Errorf("no packages found in %s", srcDir)
	}
	pkg := pkgs[0]
	if len(pkg.Errors) > 0 {
		return nil, nil, pkg.Errors[0]
	}

	// Lookup the specified type in the package scope.
	obj := pkg.Types.Scope().Lookup(typeName)
	if obj == nil {
		return nil, nil, fmt.Errorf("type %q not found in %s", typeName, srcDir)
	}

	named, ok := obj.Type().(*types.Named)
	if !ok {
		return nil, nil, fmt.Errorf("type %q is not a named type", typeName)
	}

	// Extract ES field types from the optional Mapping() method.
	// We pass pkg.Syntax (the parsed AST files) to maintain compatibility with AST-based method extraction.
	mappingTypes := extractMappingMethod(pkg.Syntax, typeName)

	var entries []fieldEntry
	extractStructFields(named, "", mappingTypes, &entries)

	// Deduplicate entries (since injected multi-fields might overlap)
	seen := make(map[string]bool)
	var uniqueEntries []fieldEntry
	for _, e := range entries {
		if !seen[e.Path] {
			seen[e.Path] = true
			uniqueEntries = append(uniqueEntries, e)
		}
	}

	sort.Slice(uniqueEntries, func(i, j int) bool {
		return uniqueEntries[i].Path < uniqueEntries[j].Path
	})

	return uniqueEntries, pkg.Syntax, nil
}

// extractStructFields uses go/types to recursively walk the named struct
// and append fieldEntry values for every JSON-visible field.
// This approach safely traverses embedded structs across different packages.
func extractStructFields(t types.Type, prefix string, mappingTypes map[string]string, entries *[]fieldEntry) {
	strct, ok := resolveStruct(t)
	if !ok {
		return
	}

	for i := 0; i < strct.NumFields(); i++ {
		field := strct.Field(i)
		tag := reflect.StructTag(strct.Tag(i))
		jsonTag := tag.Get("json")

		if jsonTag == "-" {
			continue
		}

		jsonName := strings.Split(jsonTag, ",")[0]
		if jsonName == "" {
			if field.Anonymous() {
				// Anonymous embedded field: inline its fields at the same nesting level.
				extractStructFields(field.Type(), prefix, mappingTypes, entries)
				continue
			}
			jsonName = field.Name()
		}

		// Unexported fields that are not embedded must be skipped.
		if !field.Exported() && !field.Anonymous() {
			continue
		}

		path := jsonName
		if prefix != "" {
			path = prefix + "." + jsonName
		}

		// When the element type is a known struct, recurse into it.
		elemStruct, isStruct := resolveStruct(field.Type())
		if isStruct {
			esType := "object"
			if isSlice(field.Type()) {
				esType = "nested"
			}
			// Allow Mapping() to override the derived type.
			if override, ok := mappingTypes[path]; ok {
				esType = override
			}
			*entries = append(*entries, fieldEntry{
				ConstName: toPascalCase(path),
				FieldName: toStructFieldName(path),
				Path:      path,
				Type:      esType,
			})
			extractStructFields(elemStruct, path, mappingTypes, entries)
			continue
		}

		// Leaf field — use type from Mapping() if available, otherwise "unknown".
		esType := "unknown"
		if override, ok := mappingTypes[path]; ok {
			esType = override
		}
		*entries = append(*entries, fieldEntry{
			ConstName: toPascalCase(path),
			FieldName: toStructFieldName(path),
			Path:      path,
			Type:      esType,
		})

		// Inject any sub-fields (like .keyword or .ngram_exact) defined in Mapping()
		// that extend this path.
		prefixDot := path + "."
		for mPath, mType := range mappingTypes {
			if strings.HasPrefix(mPath, prefixDot) {
				*entries = append(*entries, fieldEntry{
					ConstName: toPascalCase(mPath),
					FieldName: toStructFieldName(mPath),
					Path:      mPath,
					Type:      mType,
				})
			}
		}
	}
}

// resolveStruct recursively unwraps pointers, slices, arrays, and named types
// to find the underlying types.Struct. It leverages types.Unalias to fully support
// Go 1.26 type aliases. It intentionally prevents expanding specific domain types
// like time.Time.
func resolveStruct(t types.Type) (*types.Struct, bool) {
	for {
		t = types.Unalias(t)
		switch u := t.(type) {
		case *types.Pointer:
			t = u.Elem()
		case *types.Slice:
			t = u.Elem()
		case *types.Array:
			t = u.Elem()
		case *types.Named:
			if pkg := u.Obj().Pkg(); pkg != nil {
				if pkg.Path() == "time" && u.Obj().Name() == "Time" {
					return nil, false
				}
			}
			t = u.Underlying()
		case *types.Struct:
			return u, true
		default:
			return nil, false
		}
	}
}

// isSlice correctly traverses type definitions to check if the
// outermost type represents a variable-length slice. Fixed-length arrays
// return false.
func isSlice(t types.Type) bool {
	for {
		t = types.Unalias(t)
		switch u := t.(type) {
		case *types.Pointer:
			t = u.Elem()
		case *types.Named:
			t = u.Underlying()
		case *types.Slice: // *types.Array を除外し、Slice のみ true にする
			return true
		default:
			return false
		}
	}
}

// derefTypeName unwraps pointer, slice, and array wrappers in the AST and returns
// the base type identifier name. It returns "" for qualified (selector) expressions.
func derefTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return derefTypeName(t.X)
	case *ast.ArrayType:
		return derefTypeName(t.Elt)
	}
	return ""
}

// extractMappingMethod searches the parsed files for a method named
// "Mapping" with a value or pointer receiver of the given type name.
func extractMappingMethod(files []*ast.File, typeName string) map[string]string {
	fieldTypes := make(map[string]string)
	for _, file := range files {
		ast.Inspect(file, func(n ast.Node) bool {
			fd, ok := n.(*ast.FuncDecl)
			if !ok {
				return true
			}
			if fd.Recv == nil || fd.Name.Name != "Mapping" || fd.Body == nil {
				return true
			}
			for _, recv := range fd.Recv.List {
				if derefTypeName(recv.Type) == typeName {
					parseMappingBody(fd.Body, fieldTypes)
					return false // Break early within this file
				}
			}
			return true
		})
	}
	return fieldTypes
}

// extractStringReturnMethod searches the parsed files for a method with the given
// name on the given type.
func extractStringReturnMethod(files []*ast.File, typeName, methodName string) (string, bool) {
	var result string
	var found bool
	for _, file := range files {
		ast.Inspect(file, func(n ast.Node) bool {
			if found {
				return false
			}
			fd, ok := n.(*ast.FuncDecl)
			if !ok {
				return true
			}
			if fd.Recv == nil || fd.Name.Name != methodName || fd.Body == nil {
				return true
			}
			for _, recv := range fd.Recv.List {
				if derefTypeName(recv.Type) == typeName {
					if v, ok := extractSingleStringReturn(fd.Body); ok {
						result = v
						found = true
						return false
					}
				}
			}
			return true
		})
		if found {
			break
		}
	}
	return result, found
}

// extractSingleStringReturn extracts the string value from a method body that
// contains a single return statement. It handles both a plain string literal
// ("product") and a type-conversion call wrapping a string literal
// (estype.Alias("product"), estype.Index("product-000001")).
func extractSingleStringReturn(body *ast.BlockStmt) (string, bool) {
	for _, stmt := range body.List {
		ret, ok := stmt.(*ast.ReturnStmt)
		if !ok {
			continue
		}
		if len(ret.Results) != 1 {
			continue
		}
		return extractStringExpr(ret.Results[0])
	}
	return "", false
}

// extractStringExpr extracts the underlying string value from an expression that
// is either a basic string literal or a single-argument call wrapping one
// (e.g. estype.Alias("product") or Alias("product")).
func extractStringExpr(expr ast.Expr) (string, bool) {
	switch e := expr.(type) {
	case *ast.BasicLit:
		if e.Kind != token.STRING {
			return "", false
		}
		return strings.Trim(e.Value, `"`), true
	case *ast.CallExpr:
		if len(e.Args) != 1 {
			return "", false
		}
		return extractStringExpr(e.Args[0])
	}
	return "", false
}

// parseMappingBody extracts field path→type pairs from the body of a
// Mapping() method.
func parseMappingBody(body *ast.BlockStmt, out map[string]string) {
	for _, stmt := range body.List {
		ret, ok := stmt.(*ast.ReturnStmt)
		if !ok {
			continue
		}
		if len(ret.Results) != 1 {
			continue
		}
		mappingLit, ok := ret.Results[0].(*ast.CompositeLit)
		if !ok {
			continue
		}
		// Look for the "Fields" key in the outer composite literal.
		for _, elt := range mappingLit.Elts {
			kv, ok := elt.(*ast.KeyValueExpr)
			if !ok {
				continue
			}
			key, ok := kv.Key.(*ast.Ident)
			if !ok {
				continue
			}
			if key.Name != "Fields" {
				continue
			}
			// The value should be a slice composite literal.
			fieldSlice, ok := kv.Value.(*ast.CompositeLit)
			if !ok {
				continue
			}
			for _, fieldElt := range fieldSlice.Elts {
				fieldLit, ok := fieldElt.(*ast.CompositeLit)
				if !ok {
					continue
				}
				var path, esType string
				for _, fElt := range fieldLit.Elts {
					fkv, ok := fElt.(*ast.KeyValueExpr)
					if !ok {
						continue
					}
					fKey, ok := fkv.Key.(*ast.Ident)
					if !ok {
						continue
					}
					switch fKey.Name {
					case "Path":
						switch bl := fkv.Value.(type) {
						case *ast.BasicLit:
							if bl.Kind != token.STRING {
								continue
							}
							path = strings.Trim(bl.Value, `"`)
						default:
							continue
						}
					case "Property":
						esType = propertyValueTypeName(fkv.Value)
					}
				}
				if path != "" && esType != "" {
					out[path] = esType
				}
			}
		}
	}
}

// propertyValueTypeName extracts the Elasticsearch type name from an AST
// expression used as the Property field of an estype.MappingField literal.
// It handles three forms:
//   - A [estype.FieldType] conversion: FieldType("integer") or estype.FieldType("integer")
//   - A constructor call: NewTextProperty(...) or estype.NewTextProperty(...);
//     the ES type name is derived from the constructor function name.
//   - A plain string literal: "integer" (accepted for resilience when parsing
//     code that predates the [estype.FieldType] introduction).
func propertyValueTypeName(expr ast.Expr) string {
	call, ok := expr.(*ast.CallExpr)
	if !ok {
		// Plain string literal fallback.
		bl, ok := expr.(*ast.BasicLit)
		if !ok {
			return ""
		}
		if bl.Kind != token.STRING {
			return ""
		}
		return strings.Trim(bl.Value, `"`)
	}
	// Detect FieldType("...") or estype.FieldType("...") conversion calls.
	if name := fieldTypeFuncName(call.Fun); name == "FieldType" {
		if len(call.Args) != 1 {
			return ""
		}
		bl, ok := call.Args[0].(*ast.BasicLit)
		if !ok {
			return ""
		}
		if bl.Kind != token.STRING {
			return ""
		}
		return strings.Trim(bl.Value, `"`)
	}
	// Fall through to constructor call detection.
	return propertyCallTypeName(call.Fun)
}

// fieldTypeFuncName returns the simple function name from an expression if it
// is an identifier or selector (e.g. both "FieldType" and "estype.FieldType"
// return "FieldType").  Returns "" for any other expression shape.
func fieldTypeFuncName(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.SelectorExpr:
		return e.Sel.Name
	}
	return ""
}

// propertyCallTypeName derives the Elasticsearch type name from the function
// expression of a NewXxxProperty constructor call.
// The function may be an unqualified identifier (NewTextProperty) or a selector
// expression (estype.NewTextProperty, esv8.NewTextProperty, etc.).
// Returns "" when the expression does not match the New…Property pattern.
func propertyCallTypeName(expr ast.Expr) string {
	var name string
	switch e := expr.(type) {
	case *ast.Ident:
		name = e.Name
	case *ast.SelectorExpr:
		name = e.Sel.Name
	}
	if !strings.HasPrefix(name, "New") || !strings.HasSuffix(name, "Property") {
		return ""
	}
	// Extract the PascalCase type fragment between "New" and "Property".
	middle := name[3 : len(name)-8]
	if middle == "" {
		return ""
	}
	return pascalToSnake(middle)
}

// pascalToSnake converts a PascalCase string to snake_case.
// Used to derive an Elasticsearch type name from a Go constructor name fragment.
// Examples:
//
//	"Text"        → "text"
//	"Keyword"     → "keyword"
//	"DenseVector" → "dense_vector"
func pascalToSnake(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 4)
	for i := 0; i < len(s); i++ {
		c := s[i]
		if i > 0 && c >= 'A' && c <= 'Z' {
			b.WriteByte('_')
		}
		if c >= 'A' && c <= 'Z' {
			b.WriteByte(c + 32) // to lower
		} else {
			b.WriteByte(c)
		}
	}
	return b.String()
}
