// generator generates api_coverage_test.go for the esv8 package.
//
// It reads the Elasticsearch API specification (schema.json) from the
// elastic/elasticsearch-specification repository, maps each endpoint name to an
// expected Go method name on the ESClient interface, and writes a test file that
// reports which spec endpoints are not yet covered.
//
// Usage:
//
//	go run ./generator                      # downloads latest schema from GitHub
//	go run ./generator -schema /path/to/schema.json  # use a local copy
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"strings"
	"text/template"
)

const (
	defaultSchemaURL = "https://raw.githubusercontent.com/elastic/elasticsearch-specification/main/output/schema/schema.json"
	// outputFile is relative to the package directory where go generate is invoked
	// (i.e. the directory containing esclient.go, which is esv8/).
	outputFile = "api_coverage_test.go"
)

// Schema mirrors the top-level structure of schema.json.
type Schema struct {
	Endpoints []Endpoint `json:"endpoints"`
}

// Endpoint represents a single API endpoint defined in the specification.
type Endpoint struct {
	Name string `json:"name"`
}

// toMethodName converts a spec endpoint name to the expected Go method name.
// Examples:
//
//	"search"             → "Search"
//	"indices.create"     → "IndicesCreate"
//	"indices.put_alias"  → "IndicesPutAlias"
//	"_internal.get_desired_nodes" → "InternalGetDesiredNodes"
func toMethodName(name string) string {
	parts := strings.Split(name, ".")
	var result []string
	for _, part := range parts {
		// Strip leading underscores from namespace segments (e.g. "_internal").
		part = strings.TrimLeft(part, "_")
		if part == "" {
			continue
		}
		// Convert snake_case to PascalCase.
		subParts := strings.Split(part, "_")
		for _, sp := range subParts {
			if sp == "" {
				continue
			}
			result = append(result, strings.ToUpper(sp[:1])+sp[1:])
		}
	}
	return strings.Join(result, "")
}

// endpointEntry is passed to the template for each spec endpoint.
type endpointEntry struct {
	SpecName   string
	MethodName string
}

// templateData is the data passed to the code-generation template.
type templateData struct {
	Endpoints []endpointEntry
}

var testTemplate = template.Must(template.New("coverage").Parse(`// Code generated by "go generate"; DO NOT EDIT.
//
// Run "go generate ./..." from the esv8 package directory to regenerate.
// Source: elastic/elasticsearch-specification schema.json
package esv8_test

import (
	"reflect"
	"testing"

	"github.com/tomtwinkle/es-typed-go/esv8"
)

// specEndpoints lists every API endpoint defined in the Elasticsearch
// specification alongside the method name we expect on the ESClient interface.
// This is an informational coverage test: missing entries are logged but do
// not cause the test to fail, because this client intentionally wraps only a
// curated subset of the full API surface.
var specEndpoints = []struct {
	SpecName   string // name as in elasticsearch-specification
	MethodName string // expected method name on esv8.ESClient
}{
{{- range .Endpoints}}
	{"{{.SpecName}}", "{{.MethodName}}"},
{{- end}}
}

// TestAPICoverage reports which Elasticsearch spec endpoints have a
// corresponding method on the ESClient interface and which do not.
// Run with -v to see the full list of uncovered endpoints.
func TestAPICoverage(t *testing.T) {
	t.Parallel()
	ifaceType := reflect.TypeOf((*esv8.ESClient)(nil)).Elem()

	var covered, missing int
	for _, ep := range specEndpoints {
		_, ok := ifaceType.MethodByName(ep.MethodName)
		if ok {
			covered++
		} else {
			missing++
			t.Logf("NOT COVERED  spec=%-55q expected_method=%q", ep.SpecName, ep.MethodName)
		}
	}

	total := covered + missing
	pct := float64(covered) / float64(total) * 100
	t.Logf("API coverage: %d/%d (%.1f%%) spec endpoints have a matching ESClient method", covered, total, pct)
}
`))

func main() {
	schemaPath := flag.String("schema", "", "path to local schema.json; downloads from GitHub if empty")
	flag.Parse()

	var data []byte
	var err error

	if *schemaPath != "" {
		data, err = os.ReadFile(*schemaPath)
		if err != nil {
			log.Fatalf("failed to read %s: %v", *schemaPath, err)
		}
	} else {
		log.Printf("downloading schema from %s …", defaultSchemaURL)
		resp, err := http.Get(defaultSchemaURL) //nolint:noctx
		if err != nil {
			log.Fatalf("failed to download schema: %v", err)
		}
		defer resp.Body.Close()
		data, err = io.ReadAll(resp.Body)
		if err != nil {
			log.Fatalf("failed to read response body: %v", err)
		}
		log.Printf("downloaded %d bytes", len(data))
	}

	var schema Schema
	if err := json.Unmarshal(data, &schema); err != nil {
		log.Fatalf("failed to parse schema.json: %v", err)
	}

	entries := make([]endpointEntry, 0, len(schema.Endpoints))
	for _, ep := range schema.Endpoints {
		entries = append(entries, endpointEntry{
			SpecName:   ep.Name,
			MethodName: toMethodName(ep.Name),
		})
	}

	var buf bytes.Buffer
	if err := testTemplate.Execute(&buf, templateData{Endpoints: entries}); err != nil {
		log.Fatalf("template execution failed: %v", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("go/format failed: %v\n\nGenerated source:\n%s", err, buf.String())
	}

	if err := os.WriteFile(outputFile, formatted, 0o644); err != nil {
		log.Fatalf("failed to write %s: %v", outputFile, err)
	}

	fmt.Printf("wrote %s (%d endpoints)\n", outputFile, len(entries))
}
