package main

import (
	"bytes"
	"encoding/json"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"gotest.tools/v3/assert"
)

func TestToMethodName(t *testing.T) {
	t.Parallel()

	tests := map[string]struct {
		input string
		want  string
	}{
		"simple": {
			input: "search",
			want:  "Search",
		},
		"namespace": {
			input: "indices.create",
			want:  "IndicesCreate",
		},
		"snake_case": {
			input: "indices.put_alias",
			want:  "IndicesPutAlias",
		},
		"leading_underscore_namespace": {
			input: "_internal.get_desired_nodes",
			want:  "InternalGetDesiredNodes",
		},
		"multiple_empty_segments": {
			input: "._internal..get__desired__nodes.",
			want:  "InternalGetDesiredNodes",
		},
		"only_underscores": {
			input: "___",
			want:  "",
		},
		"empty": {
			input: "",
			want:  "",
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, toMethodName(tt.input), tt.want)
		})
	}
}

func TestTemplateExecuteAndFormat(t *testing.T) {
	t.Parallel()

	data := templateData{
		Endpoints: []endpointEntry{
			{SpecName: "search", MethodName: "Search"},
			{SpecName: "indices.put_alias", MethodName: "IndicesPutAlias"},
			{SpecName: "_internal.get_desired_nodes", MethodName: "InternalGetDesiredNodes"},
		},
	}

	var buf bytes.Buffer
	err := testTemplate.Execute(&buf, data)
	assert.NilError(t, err)

	formatted, err := format.Source(buf.Bytes())
	assert.NilError(t, err)

	got := string(formatted)

	assert.Assert(t, strings.Contains(got, `// Code generated by "go generate"; DO NOT EDIT.`))
	assert.Assert(t, strings.Contains(got, "package esv8_test"))
	assert.Assert(t, strings.Contains(got, `"github.com/tomtwinkle/es-typed-go/esv8"`))
	assert.Assert(t, strings.Contains(got, `{"search", "Search"}`))
	assert.Assert(t, strings.Contains(got, `{"indices.put_alias", "IndicesPutAlias"}`))
	assert.Assert(t, strings.Contains(got, `{"_internal.get_desired_nodes", "InternalGetDesiredNodes"}`))
	assert.Assert(t, strings.Contains(got, "func TestAPICoverage(t *testing.T)"))
	assert.Assert(t, strings.Contains(got, "t.Parallel()"))
}

func TestTemplateExecuteWithNoEndpoints(t *testing.T) {
	t.Parallel()

	var buf bytes.Buffer
	err := testTemplate.Execute(&buf, templateData{})
	assert.NilError(t, err)

	formatted, err := format.Source(buf.Bytes())
	assert.NilError(t, err)

	got := string(formatted)

	assert.Assert(t, strings.Contains(got, "var specEndpoints = []struct {"))
	assert.Assert(t, strings.Contains(got, "MethodName string"))
	assert.Assert(t, strings.Contains(got, "func TestAPICoverage(t *testing.T)"))
}

func TestEndpointEntriesFromSchema(t *testing.T) {
	t.Parallel()

	schema := Schema{
		Endpoints: []Endpoint{
			{Name: "search"},
			{Name: "indices.create"},
			{Name: "_internal.get_desired_nodes"},
		},
	}

	entries := make([]endpointEntry, 0, len(schema.Endpoints))
	for _, ep := range schema.Endpoints {
		entries = append(entries, endpointEntry{
			SpecName:   ep.Name,
			MethodName: toMethodName(ep.Name),
		})
	}

	assert.Equal(t, len(entries), 3)
	assert.Equal(t, entries[0].SpecName, "search")
	assert.Equal(t, entries[0].MethodName, "Search")
	assert.Equal(t, entries[1].SpecName, "indices.create")
	assert.Equal(t, entries[1].MethodName, "IndicesCreate")
	assert.Equal(t, entries[2].SpecName, "_internal.get_desired_nodes")
	assert.Equal(t, entries[2].MethodName, "InternalGetDesiredNodes")
}

func TestSchemaJSONUnmarshal(t *testing.T) {
	t.Parallel()

	var schema Schema
	err := json.Unmarshal([]byte(`{"endpoints":[{"name":"search"},{"name":"indices.put_alias"}]}`), &schema)
	assert.NilError(t, err)

	assert.Equal(t, len(schema.Endpoints), 2)
	assert.Equal(t, schema.Endpoints[0].Name, "search")
	assert.Equal(t, schema.Endpoints[1].Name, "indices.put_alias")
}

func TestMainWithLocalSchemaWritesOutput(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	schemaPath := filepath.Join(tmpDir, "schema.json")

	err := os.WriteFile(schemaPath, []byte(`{"endpoints":[{"name":"search"},{"name":"indices.put_alias"},{"name":"_internal.get_desired_nodes"}]}`), 0o644)
	assert.NilError(t, err)

	cmd := exec.Command("go", "run", ".", "-schema", schemaPath)
	cmd.Dir = "."
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err = cmd.Run()
	assert.NilError(t, err)

	outPath := filepath.Join(cmd.Dir, outputFile)
	t.Cleanup(func() {
		_ = os.Remove(outPath)
	})

	generated, err := os.ReadFile(outPath)
	assert.NilError(t, err)

	src := string(generated)
	assert.Assert(t, strings.Contains(stdout.String(), "wrote "+outputFile+" (3 endpoints)"))
	assert.Assert(t, strings.Contains(src, "package esv8_test"))
	assert.Assert(t, strings.Contains(src, `{"search", "Search"}`))
	assert.Assert(t, strings.Contains(src, `{"indices.put_alias", "IndicesPutAlias"}`))
	assert.Assert(t, strings.Contains(src, `{"_internal.get_desired_nodes", "InternalGetDesiredNodes"}`))
	assert.Assert(t, strings.Contains(src, "func TestAPICoverage(t *testing.T)"))
}

func TestMainWithMissingSchemaFails(t *testing.T) {
	t.Parallel()

	missingPath := filepath.Join(t.TempDir(), "missing-schema.json")

	cmd := exec.Command("go", "run", ".", "-schema", missingPath)
	cmd.Dir = "."
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	assert.Assert(t, err != nil)
	assert.Assert(t, strings.Contains(stderr.String(), "failed to read "+missingPath))
}

func TestMainWithInvalidSchemaFails(t *testing.T) {
	t.Parallel()

	tmpDir := t.TempDir()
	schemaPath := filepath.Join(tmpDir, "schema.json")

	err := os.WriteFile(schemaPath, []byte(`{invalid json`), 0o644)
	assert.NilError(t, err)

	cmd := exec.Command("go", "run", ".", "-schema", schemaPath)
	cmd.Dir = "."
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err = cmd.Run()
	assert.Assert(t, err != nil)
	assert.Assert(t, strings.Contains(stderr.String(), "failed to parse schema.json"))
}
