// Code generated by estyped; DO NOT EDIT.

package esmodel

import "github.com/tomtwinkle/es-typed-go/estype"

// Product provides typed field names for the Elasticsearch index mapping.
var Product = struct {
	Category    estype.Field
	Date        estype.Field
	Id          estype.Field
	Items       estype.Field
	Items_Name  estype.Field
	Items_Value estype.Field
	Price       estype.Field
	Status      estype.Field
	Tags        estype.Field
	Title       estype.Field
}{
	Category:    "category",
	Date:        "date",
	Id:          "id",
	Items:       "items",
	Items_Name:  "items.name",
	Items_Value: "items.value",
	Price:       "price",
	Status:      "status",
	Tags:        "tags",
	Title:       "title",
}
